name: "bert_encoder"
platform: "onnxruntime_onnx"
max_batch_size: 0  # 배치 비활성화 (원하면 수정)

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]  # seq_len
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [ 384 ]  # 임베딩 크기 (MiniLM은 384)
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
